"""add dl_leaf_sack_registration table

Revision ID: 0d6c0a057ce4
Revises: 9fcacdbfd929
Create Date: 2026-05-06 15:56:21.507107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0d6c0a057ce4'
down_revision: Union[str, None] = '9fcacdbfd929'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dl_leaf_sack_registration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('leaf_sack_code', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('represent_id', sa.Integer(), nullable=False),
    sa.Column('represent_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('member_farmer_id', sa.Integer(), nullable=False),
    sa.Column('member_farmer_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('member_farmer_identity_card', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('dl_user_id', sa.Integer(), nullable=False),
    sa.Column('dl_user_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('sack_in_kg', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('registered_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dl_user_id'], ['dl_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dl_leaf_sack_registration_dl_user_id'), 'dl_leaf_sack_registration', ['dl_user_id'], unique=False)
    op.create_index(op.f('ix_dl_leaf_sack_registration_leaf_sack_code'), 'dl_leaf_sack_registration', ['leaf_sack_code'], unique=True)
    op.create_index(op.f('ix_dl_leaf_sack_registration_member_farmer_id'), 'dl_leaf_sack_registration', ['member_farmer_id'], unique=False)
    op.create_index(op.f('ix_dl_leaf_sack_registration_represent_id'), 'dl_leaf_sack_registration', ['represent_id'], unique=False)
    op.create_index(op.f('ix_dl_leaf_sack_registration_status'), 'dl_leaf_sack_registration', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dl_leaf_sack_registration_status'), table_name='dl_leaf_sack_registration')
    op.drop_index(op.f('ix_dl_leaf_sack_registration_represent_id'), table_name='dl_leaf_sack_registration')
    op.drop_index(op.f('ix_dl_leaf_sack_registration_member_farmer_id'), table_name='dl_leaf_sack_registration')
    op.drop_index(op.f('ix_dl_leaf_sack_registration_leaf_sack_code'), table_name='dl_leaf_sack_registration')
    op.drop_index(op.f('ix_dl_leaf_sack_registration_dl_user_id'), table_name='dl_leaf_sack_registration')
    op.drop_table('dl_leaf_sack_registration')
    # ### end Alembic commands ###
