"""add_dl_weigh_leaf_table

Revision ID: 0ee639d632a6
Revises: c3d4e5f6a7b8
Create Date: 2026-05-07 16:41:36.478550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ee639d632a6'
down_revision: Union[str, None] = 'c3d4e5f6a7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dl_weigh_leaf',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sack_registration_id', sa.Integer(), nullable=False),
    sa.Column('sack_code', sa.String(length=100), nullable=False),
    sa.Column('sack_in_kg', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=255), nullable=False),
    sa.Column('leaf_type_id', sa.Integer(), nullable=False),
    sa.Column('leaf_type_name', sa.String(length=255), nullable=False),
    sa.Column('total_in_kg', sa.Float(), nullable=False),
    sa.Column('remork', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('total_weight_in_kg', sa.Integer(), nullable=False),
    sa.Column('dl_user_id', sa.Integer(), nullable=False),
    sa.Column('dl_user_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dl_user_id'], ['dl_user.id'], ),
    sa.ForeignKeyConstraint(['sack_registration_id'], ['dl_sack_registration.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dl_weigh_leaf_dl_user_id'), 'dl_weigh_leaf', ['dl_user_id'], unique=False)
    op.create_index(op.f('ix_dl_weigh_leaf_leaf_type_id'), 'dl_weigh_leaf', ['leaf_type_id'], unique=False)
    op.create_index(op.f('ix_dl_weigh_leaf_sack_registration_id'), 'dl_weigh_leaf', ['sack_registration_id'], unique=False)
    op.create_index(op.f('ix_dl_weigh_leaf_user_id'), 'dl_weigh_leaf', ['user_id'], unique=False)
    op.create_index(op.f('ix_dl_sack_registration_member_farmer_id'), 'dl_sack_registration', ['member_farmer_id'], unique=False)
    op.create_index(op.f('ix_dl_sack_registration_represent_id'), 'dl_sack_registration', ['represent_id'], unique=False)
    op.create_index(op.f('ix_dl_sack_registration_sack_code'), 'dl_sack_registration', ['sack_code'], unique=False)
    op.create_index(op.f('ix_dl_sack_registration_status'), 'dl_sack_registration', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dl_sack_registration_status'), table_name='dl_sack_registration')
    op.drop_index(op.f('ix_dl_sack_registration_sack_code'), table_name='dl_sack_registration')
    op.drop_index(op.f('ix_dl_sack_registration_represent_id'), table_name='dl_sack_registration')
    op.drop_index(op.f('ix_dl_sack_registration_member_farmer_id'), table_name='dl_sack_registration')
    op.drop_index(op.f('ix_dl_weigh_leaf_user_id'), table_name='dl_weigh_leaf')
    op.drop_index(op.f('ix_dl_weigh_leaf_sack_registration_id'), table_name='dl_weigh_leaf')
    op.drop_index(op.f('ix_dl_weigh_leaf_leaf_type_id'), table_name='dl_weigh_leaf')
    op.drop_index(op.f('ix_dl_weigh_leaf_dl_user_id'), table_name='dl_weigh_leaf')
    op.drop_table('dl_weigh_leaf')
    # ### end Alembic commands ###
