"""Initial DDD migration

Revision ID: 3807ef6e47b2
Revises: 
Create Date: 2026-05-05 14:35:32.126363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3807ef6e47b2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _has_table(conn, table: str) -> bool:
    result = conn.execute(sa.text(
        "SELECT COUNT(*) FROM information_schema.TABLES "
        "WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = :table"
    ), {"table": table})
    return result.scalar() > 0


def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    if not _has_table(conn, 'dl_permission'):
        op.create_table('dl_permission',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_dl_permission_name'), 'dl_permission', ['name'], unique=True)
    if not _has_table(conn, 'dl_role'):
        op.create_table('dl_role',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_dl_role_name'), 'dl_role', ['name'], unique=True)
    if not _has_table(conn, 'dl_role_permission'):
        op.create_table('dl_role_permission',
        sa.Column('role_id', sa.Integer(), nullable=False),
        sa.Column('permission_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['permission_id'], ['dl_permission.id'], ),
        sa.ForeignKeyConstraint(['role_id'], ['dl_role.id'], ),
        sa.PrimaryKeyConstraint('role_id', 'permission_id')
        )
    op.create_table('dl_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['dl_role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dl_user_user_name'), 'dl_user', ['user_name'], unique=True)
    op.create_table('dl_audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('endpoint', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('method', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('headers', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['dl_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dl_audit_log_user_id'), 'dl_audit_log', ['user_id'], unique=False)
    op.create_index(op.f('ix_dl_audit_log_user_name'), 'dl_audit_log', ['user_name'], unique=False)
    op.create_table('dl_user_mfa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('otp_code', sqlmodel.sql.sqltypes.AutoString(length=6), nullable=True),
    sa.Column('otp_expiry', sa.DateTime(), nullable=True),
    sa.Column('totp_secret', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('totp_enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['dl_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dl_user_mfa_user_id'), 'dl_user_mfa', ['user_id'], unique=True)
    if not _has_table(conn, 'dl_user_token'):
        op.create_table('dl_user_token',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('user_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column('refresh_token', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('expires_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['dl_user.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_dl_user_token_refresh_token'), 'dl_user_token', ['refresh_token'], unique=False)
        op.create_index(op.f('ix_dl_user_token_user_id'), 'dl_user_token', ['user_id'], unique=False)
        op.create_index(op.f('ix_dl_user_token_user_name'), 'dl_user_token', ['user_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dl_user_token_user_name'), table_name='dl_user_token')
    op.drop_index(op.f('ix_dl_user_token_user_id'), table_name='dl_user_token')
    op.drop_index(op.f('ix_dl_user_token_refresh_token'), table_name='dl_user_token')
    op.drop_table('dl_user_token')
    op.drop_index(op.f('ix_dl_user_mfa_user_id'), table_name='dl_user_mfa')
    op.drop_table('dl_user_mfa')
    op.drop_index(op.f('ix_dl_audit_log_user_name'), table_name='dl_audit_log')
    op.drop_index(op.f('ix_dl_audit_log_user_id'), table_name='dl_audit_log')
    op.drop_table('dl_audit_log')
    op.drop_index(op.f('ix_dl_user_user_name'), table_name='dl_user')
    op.drop_table('dl_user')
    op.drop_table('dl_role_permission')
    op.drop_index(op.f('ix_dl_role_name'), table_name='dl_role')
    op.drop_table('dl_role')
    op.drop_index(op.f('ix_dl_permission_name'), table_name='dl_permission')
    op.drop_table('dl_permission')
    # ### end Alembic commands ###
