"""weigh_leaf_remove_price_calc_total_weight

Revision ID: 654778ef1c76
Revises: 0ee639d632a6
Create Date: 2026-05-07 16:58:11.038795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '654778ef1c76'
down_revision: Union[str, None] = '0ee639d632a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dl_weigh_leaf', 'total_weight_in_kg',
               existing_type=mysql.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    op.drop_column('dl_weigh_leaf', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dl_weigh_leaf', sa.Column('price', mysql.FLOAT(), nullable=False))
    op.alter_column('dl_weigh_leaf', 'total_weight_in_kg',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
