"""streamline_audit_log_and_security_updates

Revision ID: 6a931dd4f758
Revises: 3807ef6e47b2
Create Date: 2026-05-05 15:31:26.575591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a931dd4f758'
down_revision: Union[str, None] = '3807ef6e47b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop columns from dl_audit_log
    op.drop_column('dl_audit_log', 'user_name')
    op.drop_column('dl_audit_log', 'headers')
    op.drop_column('dl_audit_log', 'body')
    
    # Make user_id NOT NULL
    # Drop the FK first - MySQL refuses to MODIFY a column used in a foreign
    # key constraint (error 1832), so the constraint must be dropped and recreated.
    op.drop_constraint('dl_audit_log_ibfk_1', 'dl_audit_log', type_='foreignkey')
    op.alter_column('dl_audit_log', 'user_id',
               existing_type=sa.Integer(),
               nullable=False)
    op.create_foreign_key('dl_audit_log_ibfk_1', 'dl_audit_log', 'dl_user',
               ['user_id'], ['id'])

    # Update user_agent to TEXT
    op.alter_column('dl_audit_log', 'user_agent',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dl_audit_log', 'user_agent',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
               
    op.drop_constraint('dl_audit_log_ibfk_1', 'dl_audit_log', type_='foreignkey')
    op.alter_column('dl_audit_log', 'user_id',
               existing_type=sa.Integer(),
               nullable=True)
    op.create_foreign_key('dl_audit_log_ibfk_1', 'dl_audit_log', 'dl_user',
               ['user_id'], ['id'])

    op.add_column('dl_audit_log', sa.Column('body', sa.TEXT(), nullable=True))
    op.add_column('dl_audit_log', sa.Column('headers', sa.TEXT(), nullable=True))
    op.add_column('dl_audit_log', sa.Column('user_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###
