"""add_ip_and_ua_to_usertoken

Revision ID: 9fcacdbfd929
Revises: 6a931dd4f758
Create Date: 2026-05-05 15:45:53.844602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9fcacdbfd929'
down_revision: Union[str, None] = '6a931dd4f758'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dl_user_token', sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.add_column('dl_user_token', sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dl_user_token', 'user_agent')
    op.drop_column('dl_user_token', 'ip_address')
    # ### end Alembic commands ###
