"""Add OTP and TOTP fields

Revision ID: bbc50bdf697a
Revises: f35424d651c3
Create Date: 2026-05-02 11:29:37.544080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bbc50bdf697a'
down_revision: Union[str, None] = 'f35424d651c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_token')
    op.drop_table('audit_log')
    op.alter_column('permission', 'description',
               existing_type=mysql.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.drop_index(op.f('name'), table_name='permission')
    op.drop_index(op.f('name_2'), table_name='permission')
    op.create_index(op.f('ix_permission_name'), 'permission', ['name'], unique=True)
    op.alter_column('role', 'description',
               existing_type=mysql.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.drop_index(op.f('name'), table_name='role')
    op.drop_index(op.f('name_2'), table_name='role')
    op.create_index(op.f('ix_role_name'), 'role', ['name'], unique=True)
    op.drop_constraint(op.f('role_permission_ibfk_1'), 'role_permission', type_='foreignkey')
    op.drop_constraint(op.f('role_permission_ibfk_2'), 'role_permission', type_='foreignkey')
    op.create_foreign_key(None, 'role_permission', 'permission', ['permission_id'], ['id'])
    op.create_foreign_key(None, 'role_permission', 'role', ['role_id'], ['id'])
    op.alter_column('user', 'access_type',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text("''"))
    op.alter_column('user', 'login_type',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user', 'user',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('user', 'do_date',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('user', 'ip_address',
               existing_type=mysql.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               nullable=False)
    op.alter_column('user', 'edit_user',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('user', 'edit_do_date',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('user', 'edit_ip_address',
               existing_type=mysql.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               nullable=False)
    op.alter_column('user', 'refresh_token',
               existing_type=mysql.VARCHAR(length=512),
               type_=sqlmodel.sql.sqltypes.AutoString(length=255),
               existing_nullable=True)
    op.drop_constraint(op.f('user_role_ibfk_1'), 'user_role', type_='foreignkey')
    op.drop_constraint(op.f('user_role_ibfk_2'), 'user_role', type_='foreignkey')
    op.create_foreign_key(None, 'user_role', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'user_role', 'role', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_role', type_='foreignkey')
    op.drop_constraint(None, 'user_role', type_='foreignkey')
    op.create_foreign_key(op.f('user_role_ibfk_2'), 'user_role', 'role', ['role_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('user_role_ibfk_1'), 'user_role', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('user', 'refresh_token',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=255),
               type_=mysql.VARCHAR(length=512),
               existing_nullable=True)
    op.alter_column('user', 'edit_ip_address',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=mysql.TEXT(),
               nullable=True)
    op.alter_column('user', 'edit_do_date',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('user', 'edit_user',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('user', 'ip_address',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=mysql.TEXT(),
               nullable=True)
    op.alter_column('user', 'do_date',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('user', 'user',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('user', 'login_type',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user', 'access_type',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text("''"))
    op.drop_constraint(None, 'role_permission', type_='foreignkey')
    op.drop_constraint(None, 'role_permission', type_='foreignkey')
    op.create_foreign_key(op.f('role_permission_ibfk_2'), 'role_permission', 'permission', ['permission_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('role_permission_ibfk_1'), 'role_permission', 'role', ['role_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_role_name'), table_name='role')
    op.create_index(op.f('name_2'), 'role', ['name'], unique=False)
    op.create_index(op.f('name'), 'role', ['name'], unique=True)
    op.alter_column('role', 'description',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_permission_name'), table_name='permission')
    op.create_index(op.f('name_2'), 'permission', ['name'], unique=False)
    op.create_index(op.f('name'), 'permission', ['name'], unique=True)
    op.alter_column('permission', 'description',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.create_table('audit_log',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('endpoint', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('method', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('headers', mysql.TEXT(), nullable=True),
    sa.Column('body', mysql.TEXT(), nullable=True),
    sa.Column('ip_address', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('user_agent', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('user_token',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('refresh_token', mysql.VARCHAR(length=512), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('expires_at', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
