"""move mfa fields to separate table dl_user_mfa

Revision ID: beb65fc288d2
Revises: bbc50bdf697a
Create Date: 2026-05-04 10:06:55.420858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'beb65fc288d2'
down_revision: Union[str, None] = 'bbc50bdf697a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dl_user_mfa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('otp_code', sqlmodel.sql.sqltypes.AutoString(length=6), nullable=True),
    sa.Column('otp_expiry', sa.DateTime(), nullable=True),
    sa.Column('totp_secret', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('totp_enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dl_user_mfa_user_id'), 'dl_user_mfa', ['user_id'], unique=True)

    # Data transfer
    op.execute(
        "INSERT INTO dl_user_mfa (user_id, otp_code, otp_expiry, totp_secret, totp_enabled) "
        "SELECT id, otp_code, otp_expiry, totp_secret, totp_enabled FROM user"
    )

    # Drop columns from user table
    op.drop_column('user', 'totp_enabled')
    op.drop_column('user', 'totp_secret')
    op.drop_column('user', 'otp_expiry')
    op.drop_column('user', 'otp_code')
    
    # Optional: Fix index names if needed, but let's keep it simple
    op.create_index(op.f('ix_user_token_refresh_token'), 'user_token', ['refresh_token'], unique=False)
    op.create_index(op.f('ix_user_token_user_name'), 'user_token', ['user_name'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(op.f('ix_user_token_user_name'), table_name='user_token')
    op.drop_index(op.f('ix_user_token_refresh_token'), table_name='user_token')
    
    op.add_column('user', sa.Column('otp_code', sa.String(length=6), nullable=True))
    op.add_column('user', sa.Column('otp_expiry', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('totp_secret', sa.String(length=32), nullable=True))
    op.add_column('user', sa.Column('totp_enabled', sa.Boolean(), server_default=sa.text("'0'"), nullable=False))
    
    # Data restoration
    op.execute(
        "UPDATE user SET "
        "otp_code = (SELECT otp_code FROM dl_user_mfa WHERE dl_user_mfa.user_id = user.id), "
        "otp_expiry = (SELECT otp_expiry FROM dl_user_mfa WHERE dl_user_mfa.user_id = user.id), "
        "totp_secret = (SELECT totp_secret FROM dl_user_mfa WHERE dl_user_mfa.user_id = user.id), "
        "totp_enabled = (SELECT totp_enabled FROM dl_user_mfa WHERE dl_user_mfa.user_id = user.id)"
    )

    op.drop_index(op.f('ix_dl_user_mfa_user_id'), table_name='dl_user_mfa')
    op.drop_table('dl_user_mfa')
